
# nameday.py

dateused = input(" Date in ddmm yyyy format, without a leading 0 e.g. 511 2015 > ")

d = {
    '11':'No Name Today!',
    '12':'Aapeli',
    '13':'Elmer, Elmeri, Elmo',
    '14':'Ruut, Tiitus',
    '15':'Lea, Leea',
    '16':'Harri',
    '17':'Aku, August, Aukusti',
    '18':'Hilppa, Titta',
    '19':'Veijo, Veikka, Veikko, Veli',
    '110':'Nyyrikki',
    '111':'Kari, Karri',
    '112':'Toini',
    '113':'Nuutti',
    '114':'Sakari, Saku, Sasu',
    '115':'Solja',
    '116':'Ilmari, Ilmo',
    '117':'Anton, Antto, Anttoni, Toni',
    '118':'Laura',
    '119':'Heikki, Henna, Henni, Henri, Henriikka, Henrik, Henrikki',
    '120':'Sebastian',
    '121':'Aune, Auni, Netta, Oona',
    '122':'Visa',
    '123':'Eine, Eini, Enna, Enni',
    '124':'Senja',
    '125':'Paavali, Paavo, Paul, Pauli, Paulus',
    '126':'Joonatan',
    '127':'Viljo',
    '128':'Kaarle, Kaarlo, Kalle, Mies',
    '129':'Valtteri',
    '130':'Irja',
    '131':'Alli',
    '21':'Riitta',
    '22':'Aamu, Jemina, Lumi',
    '23':'Hugo, Valo',
    '24':'Armi, Ronja',
    '25':'Asser',
    '26':'Tea, Teija, Terhi, Terhikki, Tiia',
    '27':'Rikhard, Riku',
    '28':'Laina',
    '29':'Raija, Raisa',
    '210':'Elina, Ella, Elle, Ellen, Elna',
    '211':'Iisa, Isabella, Talvikki',
    '212':'Elma, Elmi',
    '213':'Sulho, Sulo',
    '214':'Tino, Valentin, Voitto',
    '215':'Sipi, Sippo',
    '216':'Kai',
    '217':'Karita, Rita, Väinämö, Väinö',
    '218':'Kaino',
    '219':'Eija',
    '220':'Heli, Helinä, Heljä, Hely',
    '221':'Keijo',
    '222':'Hilda, Tuuli, Tuulia, Tuulikki',
    '223':'Aslak',
    '224':'Matias, Matti',
    '225':'Tuija, Tuire, Vanessa',
    '226':'Nestori',
    '227':'Torsti',
    '228':'Onni, Sisu',
    '229':'No Name Today!',
    '31':'Alpi, Alpo, Alvi',
    '32':'Fanni, Fiona, Virva, Virve',
    '33':'Kauko',
    '34':'Ari, Arsi, Atro',
    '35':'Laila, Leila',
    '36':'Tarmo',
    '37':'Taika, Tarja, Taru',
    '38':'Vilppu',
    '39':'Auvo, Edvin',
    '310':'Aura, Auri, Aurora',
    '311':'Kalervo',
    '312':'Reijo, Reko',
    '313':'Ernesti, Erno, Tarvo',
    '314':'Malla, Matilda, Mette, Tilda',
    '315':'Risto',
    '316':'Ilkka',
    '317':'Kerttu, Kerttuli',
    '318':'Edvard, Eetu',
    '319':'Joose, Joosef, Jooseppi, Josefiina, Juuso',
    '320':'Aki, Jaakkima, Joakim, Jooa, Kim, Kimi',
    '321':'Pentti',
    '322':'Vihtori, Viktor',
    '323':'Akseli, Selina',
    '324':'Gabriel, Kaapo, Kaappo, Kaapro',
    '325':'Aava, Aija',
    '326':'Immanuel, Immo, Manne, Manu',
    '327':'Saul, Sauli',
    '328':'Armas',
    '329':'Joni, Jonne, Jonni, Joona, Joonas, Jouni',
    '330':'Usko',
    '331':'Irma, Irmeli',
    '41':'Peppi, Pulmu, Raita',
    '42':'Pellervo',
    '43':'Sampo, Veeti',
    '44':'Ukko',
    '45':'Ira, Irene, Irina, Iro',
    '46':'Jami, Vilhelm, Vilho, Vili, Viljami, Ville',
    '47':'Ahvo, Allan',
    '48':'Suoma, Suometar',
    '49':'Eeli, Eelis, Elia, Elias, Eliel, Eljas',
    '410':'Tero',
    '411':'Minea, Minka, Verna',
    '412':'Janna, Janni, Julia, Juliaana, Julius, Juuli',
    '413':'Tellervo',
    '414':'Taito',
    '415':'Linda, Tuomi',
    '416':'Jalo, Patrik',
    '417':'Otto',
    '418':'Valdemar, Valto',
    '419':'Pälvi, Pilvi',
    '420':'Lauha, Neela, Nella',
    '421':'Anselmi, Anssi',
    '422':'Aida, Alina',
    '423':'Jiri, Jori, Jyri, Jyrki, Yrjänä, Yrjö',
    '424':'Albert, Altti, Pertti',
    '425':'Markku, Marko, Markus',
    '426':'Teresa, Terttu, Tessa',
    '427':'Meea, Merja',
    '428':'Ilpo, Ilppo, Tuure',
    '429':'Teijo',
    '430':'Miia, Mira, Mirella, Mirja, Mirjami, Mirka, Mirkka, Mirva',
    '51':'Valpuri, Vappu',
    '52':'Viivi, Vuokko',
    '53':'Outi',
    '54':'Roosa, Rosa, Ruusu',
    '55':'Maini, Melina, Melissa',
    '56':'Ylermi',
    '57':'Helmi, Kastehelmi',
    '58':'Heino',
    '59':'Timi, Timo',
    '510':'Aina, Aini, Ainikki, Aino',
    '511':'Osmo',
    '512':'Lotta',
    '513':'Floora, Kukka',
    '514':'Tuula',
    '515':'Sofia, Sohvi, Sonja',
    '516':'Essi, Ester, Esteri',
    '517':'Maila, Maili, Mailis, Maisa, Rebekka',
    '518':'Eerik, Eerika, Eerikki, Eero, Erkka, Erkki',
    '519':'Amalia, Emilia, Emma, Emmi, Mila, Milja, Milka, Milla',
    '520':'Karoliina, Lila, Lilja, Lilli',
    '521':'Konsta, Konstantin, Kosti',
    '522':'Hemminki, Hemmo',
    '523':'Lyydia, Lyyli',
    '524':'Touko, Tuukka',
    '525':'Urpo',
    '526':'Miina, Mimmi, Minna, Minni, Vilhelmiina, Vilma',
    '527':'Ritva',
    '528':'Alma',
    '529':'Oiva, Oivi, Oliver, Olivia',
    '530':'Pasi',
    '531':'Helga, Helka',
    '61':'Nikodemus, Teemu',
    '62':'Venla',
    '63':'Orvokki, Viola',
    '64':'Toivo',
    '65':'Sulevi',
    '66':'Kustaa, Kustavi, Kyösti',
    '67':'Robert, Robin, Roope, Suvi',
    '68':'Salomo, Salomon',
    '69':'Ensio',
    '610':'Seppo',
    '611':'Immi, Impi',
    '612':'Esko',
    '613':'Raila, Raili',
    '614':'Kielo, Pihla',
    '615':'Moona, Viena, Vieno',
    '616':'Päivä, Päivi, Päivikki',
    '617':'Urho',
    '618':'Tapio',
    '619':'Siiri',
    '620':'Into',
    '621':'Ahti, Ahto',
    '622':'Liina, Paula, Pauliina',
    '623':'Aadolf, Aatto, Aatu',
    '624':'Jani, Janne, Johannes, Juha, Juhana, Juhani, Juho, Jukka, Jussi',
    '625':'Uuno',
    '626':'Jarkko, Jarmo, Jarno, Jere, Jeremias, Jorma',
    '627':'Elvi, Elviira',
    '628':'Leo',
    '629':'Peetu, Pekka, Pekko, Petja, Petra, Petri, Petrus, Petteri, Pietari',
    '630':'Päiviö, Päivö',
    '71':'Aaro, Aaron',
    '72':'Kukka-Maaria, Maaria, Maija, Maiju, Maikki, Mari, Maria, Marika, Meeri, Riia',
    '73':'Arvo',
    '74':'Ulla, Ulpu',
    '75':'Untamo, Unto',
    '76':'Esa, Esaias',
    '77':'Klaus, Launo',
    '78':'Turkka, Turo',
    '79':'Ilta, Jade, Jasmiina, Jasmin, Nanna',
    '710':'Saima, Saimi',
    '711':'Eleonoora, Elli, Nelli, Noora',
    '712':'Herkko, Herman, Hermanni',
    '713':'Ilari, Joel, Lari',
    '714':'Aliisa, Alisa',
    '715':'Rauna, Rauni',
    '716':'Reino, Rene',
    '717':'Ossi, Ossian',
    '718':'Riikka',
    '719':'Saara, Salla, Salli, Sara, Sari, Sarita',
    '720':'Maaret, Maarit, Margareeta, Marketta, Reeta, Reetta',
    '721':'Hanna, Hanne, Hannele, Jenna, Jenni, Joanna, Johanna, Jonna',
    '722':'Leena, Leeni, Lenita, Matleena',
    '723':'Oili, Olga',
    '724':'Kiia, Kirsi, Kirsti, Krista, Kristiina, Tiina, Tinja',
    '725':'Jaakko, Jaakob, Jaakoppi, Jimi',
    '726':'Martta',
    '727':'Heidi',
    '728':'Atso',
    '729':'Olavi, Olli, Oula, Uolevi, Uoti',
    '730':'Asta',
    '731':'Elena, Helena',
    '81':'Maire',
    '82':'Kimmo',
    '83':'Linnea, Nea, Neea, Vanamo',
    '84':'Veera',
    '85':'Salme, Sanelma',
    '86':'Keimo, Toimi',
    '87':'Lahja',
    '88':'Silva, Sylvi, Sylvia',
    '89':'Eira, Erja, Nadja',
    '810':'Lasse, Lassi, Lauri',
    '811':'Sanna, Sanni, Susanna, Susanne',
    '812':'Kiira, Klaara',
    '813':'Jesse, Okko',
    '814':'Kanerva, Onerva',
    '815':'Jaana, Jatta, Marianna, Marianne, Marita, Maritta, Marja, Marjaana, Marjatta, Marjo, Marjukka, Marjut',
    '816':'Aulis',
    '817':'Venni, Verneri',
    '818':'Leevi',
    '819':'Mauno, Maunu',
    '820':'Sami, Samu, Samuel, Samuli',
    '821':'Soini, Veini',
    '822':'Iivari, Iivo',
    '823':'Signe, Varma',
    '824':'Bertta, Perttu',
    '825':'Loviisa',
    '826':'Ilma, Ilmatar, Ilmi',
    '827':'Rauli',
    '828':'Tauno',
    '829':'Iina, Iines, Inari, Inna',
    '830':'Eemeli, Eemi, Eemil',
    '831':'Arvi',
    '91':'Pirkka',
    '92':'Justus, Sini, Sinikka',
    '93':'Soila, Soile, Soili',
    '94':'Ansa',
    '95':'Mainio, Roni',
    '96':'Asko, Felix',
    '97':'Arhippa, Arho, Milo, Miro',
    '98':'Taimi',
    '99':'Eevert, Isto, Vertti',
    '910':'Kaleva, Kalevi',
    '911':'Ale, Aleksandra, Aleksanteri, Ali, Sandra, Santeri, Santtu',
    '912':'Valma, Vilja',
    '913':'Orvo',
    '914':'Iida, Iita, Isla',
    '915':'Sirpa',
    '916':'Hellevi, Hilla, Hille, Hillevi',
    '917':'Aila, Aili',
    '918':'Tytti, Tyyne, Tyyni',
    '919':'Reija',
    '920':'Varpu, Vaula',
    '921':'Mervi',
    '922':'Mauri',
    '923':'Mielikki, Miisa, Minja',
    '924':'Alvar, Auno',
    '925':'Kullervo',
    '926':'Kuisma',
    '927':'Vesa',
    '928':'Arja, Lenni',
    '929':'Miika, Miikka, Mika, Mikael, Mikaela, Mikko, Miko, Miska',
    '930':'Sirja, Siru, Sorja',
    '101':'Raine, Rainer, Raino, Rauno',
    '102':'Valio',
    '103':'Raimo',
    '104':'Frans, Saija, Saila',
    '105':'Inka, Inkeri',
    '106':'Minttu, Pinja',
    '107':'Birgitta, Pipsa, Pirita, Piritta, Pirjo, Pirkko',
    '108':'Hilja',
    '109':'Ilona',
    '1010':'Aleksi, Aleksis',
    '1011':'Ohto, Otso',
    '1012':'Aarre, Aarto',
    '1013':'Taija, Taina, Tanja',
    '1014':'Elsa, Else, Elsi',
    '1015':'Helvi, Heta',
    '1016':'Luna, Sirkka, Sirkku, Stella',
    '1017':'Saaga, Saana, Saini',
    '1018':'Luka, Luukas, Säde, Satu',
    '1019':'Uljas',
    '1020':'Jasper, Jesper, Kasper, Kasperi, Kauno',
    '1021':'Ursula',
    '1022':'Anette, Anita, Anitta, Anja, Anniina, Nita',
    '1023':'Severi',
    '1024':'Asmo, Rasmus',
    '1025':'Sointu',
    '1026':'Amanda, Manta, Niina, Nina, Ninni',
    '1027':'Hellä, Helle, Helli, Hellin',
    '1028':'Simo',
    '1029':'Alfred, Urmas',
    '1030':'Eila',
    '1031':'Arto, Arttu, Artturi',
    '111':'Lyly, Pyry',
    '112':'Topi, Topias',
    '113':'Terho',
    '114':'Hertta',
    '115':'Reima',
    '116':'Mimosa',
    '117':'Erin, Taisto',
    '118':'Aatos',
    '119':'Teo, Teuvo',
    '1110':'Martti',
    '1111':'Panu',
    '1112':'Virpi',
    '1113':'Ano, Kristian',
    '1114':'Iiris',
    '1115':'Janette, Janika, Janina, Janita',
    '1116':'Aarne, Aarni, Aarno',
    '1117':'Einari, Eino',
    '1118':'Jousia, Max, Tenho',
    '1119':'Eliisa, Elisa, Elisabet, Elise, Liisa, Liisi',
    '1120':'Jalmari, Jari',
    '1121':'Hilma',
    '1122':'Cecilia, Seela, Selja, Silja',
    '1123':'Ismo',
    '1124':'Lemmikki, Lempi, Sivi',
    '1125':'Kaarina, Kaija, Kaisa, Kaisu, Katariina, Kati, Katja, Katri, Katriina, Riina',
    '1126':'Sisko',
    '1127':'Hilkka',
    '1128':'Heini, Kaisla',
    '1129':'Aimo',
    '1130':'Andreas, Antero, Antti, Atte',
    '121':'Oskar, Oskari',
    '122':'Anelma, Unelma, Unna',
    '123':'Meri, Vellamo',
    '124':'Aira, Airi',
    '125':'Selma',
    '126':'Niila, Niilo, Niki, Niklas, Niko, Nikolai, Nikolas',
    '127':'Sampsa',
    '128':'Kylli, Kyllikki',
    '129':'Anna, Anne, Anneli, Anni, Annika, Annikki, Annu, Annukka, Anu',
    '1210':'Jutta',
    '1211':'Daniel, Daniela, Taneli, Tatu',
    '1212':'Tuovi',
    '1213':'Seija',
    '1214':'Jouko',
    '1215':'Heimo, Nooa',
    '1216':'Aada, Adele, Auli, Aulikki',
    '1217':'Raakel',
    '1218':'Aapo, Aappo, Rami',
    '1219':'Iikka, Iiro, Iisakki, Isko',
    '1220':'Benjamin, Kerkko',
    '1221':'Tomi, Tommi, Tuomas, Tuomo',
    '1222':'Raafael',
    '1223':'Noel, Senni',
    '1224':'Aatami, Eeva, Eevi, Eveliina',
    '1225':'Tahvo, Tapani, Teppo',
    '1226':'Hannes, Hannu, Hans',
    '1227':'Piia',
    '1228':'Rauha',
    '1229':'Daavid, Taavetti, Taavi',
    '1230':'Silvo, Sylvester',
}

def nameday ():
    print(d.get(dateused))
    again()

def again():
    find_again = input ('''
Do you want to calculate again?
Please type Y or N.
''')

    if find_again.upper() == 'Y':
        nameday ()
    elif find_again.upper() == 'N':
        print('See you later.')
    else:
        again()

nameday()